### PR TITLE
chore: migrate to cli-table3

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Bump. This is still relevant.

**Comment by garbados** [comment]
Hey, checking in on this. Can you tell me more about the situation? cli-table received commits as recently as a year ago, and cli-table3 has received commits far more recently than the version on NPM. It's quite confusing and if you have a firm opinion about it, I'd like to hear it.

**Comment by DanielRuf** [comment]
Hey @garbados,

cli-table3 fixes a vulnerability, many open issues and improves a few things compared to cli-table. The code is almost the same.

We created the forked version to fix all these things as the maintainer of cli-table was unresponsive.

**Comment by garbados** [comment]
Sounds good to me! I'll get this merged.

**Pull request closed without merging**
